### PR TITLE
Remove hint style success from README

### PR DESCRIPTION
**Pull request by untitledgeese**
Hint style success does not show in GitHub, and it looks quite odd, thoughts on removing?

### CODE REVIEW

**Comment by LukasmanMHdude** [comment]
I mean, it is one litterly every page so /shrug

**Comment by LukasmanMHdude** [comment]
I've never seen it not work though, do you want to send a picture?

**Comment by AdxmGG** [comment]
its on every page and it shows on gitbook which is where everyone actually sees it..

**Comment by untitledgeese** [comment]
> I've never seen it not work though, do you want to send a picture?

Sorry for the bad wording- I meant that GitHub does not display it well, see the attached image;
image

**Comment by LukasmanMHdude** [comment]
It only works on GitBook, its not meant to render here

**Comment by LukasmanMHdude** [comment]
I'll let Adam close this though

**Comment by untitledgeese** [comment]
alright then

**Comment by AdxmGG** [comment]
smh goose

**Pull request closed without merging**
