### PR TITLE
Next batch of articles

### PR DESCRIPTION
**Pull request by LukasmanMHdude**

### CODE REVIEW

**Comment by LukasmanMHdude** [comment]
@untitledgeese I have no idea how to fix the merge issues, something with cmd line??

**Comment by untitledgeese** [comment]
Why are you deprecating the variables tutorial? It's perfectly up to date...

**Comment by LukasmanMHdude** [comment]
Oh I'm prepping for when we redo the tuts, I did that to all of them on master by accident

**Comment by untitledgeese** [comment]
> Oh I'm prepping for when we redo the tuts, I did that to all of them on master by accident

IMO we shouldn't redo tutorials like that because they're already up to date and have plenty of detail.... maybe only redo tutorials that are slightly vague and don't explain a whole lot?

**Comment by LukasmanMHdude** [comment]
Ok, so heres the problem. I already added the"old" to the master branch. These are actual changes we need, and I was trying to see if I added /old/ in front of them it could merge but no

**Pull request closed without merging**
